export const CART_LIST_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const CART_LIST_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const CART_LIST_FAIL = 'PRODUCT_DETAILS_FAIL'

export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_REMOVE_FAIL = 'CART_REMOVE_FAIL'

export const CART_EDIT_ITEM = 'CART_EDIT_ITEM'
export const CART_EDIT_FAIL = 'CART_EDIT_FAIL'
